print("Name : OM SUTARIYA")
print("Roll No. : 24BEE114")
names_set = set()
names_set.update({"Hello", "Hi", "Bye","Haha" ,"Go"})
print("After adding names:", names_set)
names_set.discard("Bye") 
names_set.add("hey")  
print("After modifying a name:", names_set)
names_set.discard("Hello")
names_set.discard("Hi")
print("After deleting two names:", names_set)
